---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
  labels:
    name: bookstore
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: bookstore
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: test
    serviceAccount: bookstore
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongodb
spec:
  mount: bookstore/static
  type: kv-v2
  path: mongodb
  destination:
    create: true
    name: mongodb
    type: Opaque
  vaultAuthRef: bookstore
  refreshAfter: 2m
  rolloutRestartTargets:
    - kind: Deployment
      name: bookstore